services:
  streamlit-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.app
    ports:
      - "8501:8501"
    environment:
      MCP_SERVER_URL: http://mcp-server:8000
    depends_on:
      - mcp-server

  mcp-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile.mcp
    ports:
      - "8000:8000"
